- hosts: all

  tasks:
    - dnf: name={{item}}
      with_items:
        - openstack-utils
        - python-swiftclient
        - memcached
        - xinetd
        - openstack-swift
        - openstack-swift-proxy
        - openstack-swift-object
        - openstack-swift-container
        - openstack-swift-account

    - lineinfile: dest=/etc/selinux/config regexp=^SELINUX= line=SELINUX=Permissive

    - command: /usr/sbin/setenforce Permissive

    - copy: src=files/etc/sysctl.d/swift.conf dest=/etc/sysctl.d/swift.conf

    - command: /usr/sbin/sysctl -p

    - template: dest=/etc/swift/{{ item }} src=files/etc/swift/{{ item }} owner=swift group=swift
      with_items:
        - object-server/1.conf
        - object-server/2.conf
        - object-server/3.conf
        - object-server/4.conf
        - container-server/1.conf
        - container-server/2.conf
        - container-server/3.conf
        - container-server/4.conf
        - account-server/1.conf
        - account-server/2.conf
        - account-server/3.conf
        - account-server/4.conf
        - container-reconciler.conf
        - object-expirer.conf
        - proxy-server.conf
        - swift.conf

    - file: path=/etc/swift/{{item}} state=absent
      with_items:
        - account-server.conf
        - container-server.conf
        - object-server.conf

    - file: path=/etc/swift/ state=directory owner=swift group=swift recurse=yes

    - file: path=/srv  state=directory

    - file: path={{ item }} state=directory owner=swift group=swift
      with_items:
        - /srv/1/node/sdb1
        - /srv/2/node/sdb2
        - /srv/3/node/sdb3
        - /srv/4/node/sdb4
        - /var/run/swift
        - /var/cache/swift
        - /var/cache/swift2
        - /var/cache/swift3
        - /var/cache/swift4

    - script: files/bin/remakerings creates=/etc/swift/object.ring.gz

    - service: name={{item}} state=started
      with_items:
        - memcached
        - xinetd
    
    - command: /usr/bin/swift-init start main creates=/var/run/swift/proxy-server.pid

    - command: '/usr/bin/swift -U test:tester -K testing -A http://127.0.0.1:8080/auth/v1.0/ post -m "temp-url-key: secret"'

    - command: '/usr/bin/swift -U test:tester -K testing -A http://127.0.0.1:8080/auth/v1.0/ post summit'

    - command: '/usr/bin/swift -U test:tester -K testing -A http://127.0.0.1:8080/auth/v1.0/ post -r ".r:*,.rlistings" public'
