Vagrant.configure(2) do |config|
  config.vm.box = "fedora22"
  config.vm.box_url = "https://download.fedoraproject.org/pub/fedora/linux/releases/22/Cloud/x86_64/Images/Fedora-Cloud-Base-Vagrant-22-20150521.x86_64.vagrant-virtualbox.box"
  config.vm.network "private_network", ip: "192.168.8.80"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  config.vm.provision "shell", inline: "dnf install -y yum-utils"
  config.vm.provision "ansible" do |ansible|
    ansible.sudo = true
    ansible.playbook = "ansible-fedora-saio.yaml"
  end
end
